workflows:
  ios:
    name: Build and release iOS
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: "HiApp"
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS App
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                      -scheme Runner \
                      -configuration Release \
                      -sdk iphoneos \
                      archive \
                      -archivePath $CM_BUILD_DIR/Runner.xcarchive
          xcodebuild -exportArchive \
                      -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                      -exportOptionsPlist ios/ExportOptions.plist \
                      -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
